# Project
version=1.3.5
group=org.infernalstudios.shieldexp
java_version=17

# Common
minecraft_version=1.20.1
mod_name=Shield Expansion
mod_author=Infernal Studios
mod_id=shieldexp
license=Apache License 2.0
credits=Kuraion - Developer\nHellionGames, CaelTheQuail, LudoCrypt - Developer\nNekomaster1000 - Conceptualiser, Artist\nevanbones - Maintainer\nEB Mario - Concept Collaborator
description=Adds tiers and parrying to shields for more interesting combat!
minecraft_version_range=[1.20.1, 1.20.2)

# Parchment
parchment_minecraft=1.20.1
parchment_version=2023.09.03

# Required Dependencies
mixinextras_version=0.3.5

# Optional Dependencies
cloth_config_version=11.1.118
mod_menu_version=7.2.2
emi_version=1.0.4+1.20.1
better_combat_version=1.8.6+1.20.1

# Fabric
fabric_version=0.92.1+1.20.1
fabric_loader_version=0.16.9

# Forge
forge_version=47.2.30
forge_loader_version_range=[47,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.vfs.watch=true