# Project
version=1.3.1
group=org.infernalstudios.shieldexp
java_version=21

# Common
minecraft_version=1.21.1
mod_name=Shield Expansion
mod_author=Infernal Studios
mod_id=shieldexp
license=Apache License 2.0
credits=Kuraion - Developer\nHellionGames, CaelTheQuail, LudoCrypt - Developer\nNekomaster1000 - Conceptualiser, Artist\nevanbones - Developer\nEB Mario - Concept Collaborator
description=Adds tiers and parrying to shields for more interesting combat!
minecraft_version_range=[1.21, 1.21.1)
neo_form_version=1.21.1-20240808.144430

# Parchment
parchment_minecraft=1.21
parchment_version=2024.11.10

# Optional Dependencies
cloth_config_version=15.0.140
mod_menu_version=11.0.3
emi_version=1.1.22+1.21.1
better_combat_version=2.3.1+1.21.1

# Fabric
fabric_version=0.116.6+1.21.1
fabric_loader_version=0.16.9

# NeoForge
neoforge_version=21.1.80
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.vfs.watch=true