plugins {
    id 'multiloader-common'
    id 'net.neoforged.moddev.legacyforge'
}

legacyForge {
    mcpVersion = minecraft_version
    if (file("src/main/resources/META-INF/accesstransformer.cfg").exists()) {
        accessTransformers = ["src/main/resources/META-INF/accesstransformer.cfg"]
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
}

dependencies {
    // Cloth Config
    compileOnly "me.shedaniel.cloth:cloth-config-forge:${cloth_config_version}"

    // Better Combat
    compileOnly "maven.modrinth:better-combat:${better_combat_version}-forge"

    compileOnly "io.github.llamalad7:mixinextras-common:${mixinextras_version}"
    compileOnly 'org.jetbrains:annotations:26.0.2-1'
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    compileOnly group: 'org.ow2.asm', name: 'asm-tree', version: '9.6'
    implementation group: 'com.google.code.findbugs', name: 'jsr305', version: '3.0.1'
}

configurations {
    commonJava {
        canBeResolved = false
        canBeConsumed = true
    }
    commonResources {
        canBeResolved = false
        canBeConsumed = true
    }
}

artifacts {
    commonJava sourceSets.main.java.sourceDirectories.singleFile
    commonResources sourceSets.main.resources.sourceDirectories.singleFile
}